---
title: "20160409Demo"
author: "David Chiu"
date: "2016年4月9日"
output: html_document
---

### GET appledaily
```{r}
library(httr)
res <- GET('http://www.appledaily.com.tw/realtimenews/section/new/')
res

```

### POST THSRC
```{r}
library(httr)
url <- "https://www.thsrc.com.tw/tw/TimeTable/SearchResult"
payload <- list(
  StartStation='977abb69-413a-4ccf-a109-0272c24fd490',
  EndStation='fbd828d8-b1da-4b06-a3bd-680cdca4d2cd',
  SearchDate='2016/04/09',
  SearchTime='15:00',
  SearchWay='DepartureInMandarin'
)

res<-POST(url, body=payload, encode="form")
res

```


### Markdown Sample

# heading 1
## heading 2
### heading 3

- list item
    1. item1
    2. item2
    3. item3
- list item2

### To understand Markdown
- http://markdown.tw/

### List Operation
```{r}
p1 <- list(height = 170, weight = 60, name ="annie" )
p1
p1$height

```

### GET Taiwan Railroad

```{r}
library(httr)
qoo <- GET('http://twtraffic.tra.gov.tw/twrail/SearchResult.aspx?searchtype=0&searchdate=2016/04/09&fromstation=1810&tostation=1008&trainclass=%271100%27,%271101%27,%271102%27,%271107%27,%271108%27,%271110%27,%271120%27&fromtime=0600&totime=2359')
qoo

```


### magrittr

```{r}

data(iris)
?iris
View(iris)
a <- head(iris)
b <- a[3,]
c<-b['Sepal.Length']
tail(c,1)

tail(head(iris)[3,]['Sepal.Length'],1)



#install.packages("magrittr")
library(magrittr)
iris %>% head() %>% .[3,] %>% .['Sepal.Length'] %>% tail(1)
```

### rvest
```{r}
library(httr)
library(rvest)
res <- GET('http://www.appledaily.com.tw/realtimenews/section/new/')

# harvest by tag name : time
content(res) %>% html_nodes('time') %>% .[1]
content(res) %>% html_nodes('h1.dddd time') 
content(res) %>% html_nodes('#maincontent > div.thoracis > div.abdominis.rlby.clearmen > h1 > time') %>% html_text()

# harvest by css ID: maincontent
content(res) %>% html_nodes('#maincontent') 


# harvest by css class: rtddt
content(res) %>% html_nodes('.rtddt') 

# harvest by list li with css class: rtddt
content(res) %>% html_nodes('li.rtddt') 
```

### Comparing httr GET and rvest read_html
```{r}
library(httr)
library(rvest)
res <- GET('http://www.appledaily.com.tw/realtimenews/section/new/')

# using httr GET
content(res) %>% html_nodes('#maincontent > div.thoracis > div.abdominis.rlby.clearmen > h1 > time') %>% html_text()

# using rvest read_html 
read_html('http://www.appledaily.com.tw/realtimenews/section/new/')  %>% html_nodes('#maincontent > div.thoracis > div.abdominis.rlby.clearmen > h1 > time') %>% html_text()
```

### Get appledaily list
```{r}
url <- 'http://www.appledaily.com.tw/realtimenews/section/new/'
Sys.getlocale()
li <- read_html(url, encoding = 'UTF-8') %>% html_nodes('li.rtddt')
li %>% html_nodes('a')
datetime <- li %>% html_nodes('time') %>% html_text() %>%iconv(from='UTF-8', to='UTF-8')
h1 <- li %>% html_nodes('h1') %>% html_text() %>%iconv(from='UTF-8', to='UTF-8') 
h2 <- li %>% html_nodes('h2') %>% html_text() %>%iconv(from='UTF-8', to='UTF-8')

appledf <- data.frame(datetime = datetime, title = h1, category = h2 )
appledf[  appledf$category == '娛樂',   ]

```

### Data Frame Demo
```{r}
name <-'mike' 
name

name <- c('mike', 'alice', 'john')
height <- c(170, 162, 180)
weight <- c(66,52,77)

df<- data.frame(namec = name, heightc = height, weightc = weight)

df[1,]
df[1, 'heightc']
df[df$weightc >= 60, ]
df
View(df)

# get second row 
df[2,]

# get column named after heightc
df[,2]
df$heightc

#get alice's height
df[2,'heightc']

# get height over 170
df[ df$heightc >=170  , c('namec', 'heightc')  ]

# get bmi of these three, bmi = weight / (height^2)
df$bmi = df$weightc / ((df$heightc / 100)^2)
df
max(df$bmi)
summary(df$bmi)
```


