---
title: "20160416Demo"
author: "David Chiu"
date: "2016年4月15日"
output: html_document
---
# 蘋果日報完整爬蟲

## 取得蘋果內容頁面
```{r}
library(rvest)

getArticle <- function(ele){
  e <- read_html(ele) 
  content= e %>% html_nodes('.articulum.trans') %>% 
    html_text() %>% 
    iconv(from='UTF-8', to='UTF-8')
  title <- e %>% html_nodes('#h1') %>% 
    html_text() %>% 
    iconv(from='UTF-8', to='UTF-8')
  dt <- e %>% html_nodes('.gggs time') %>% 
    html_text() %>% 
    iconv(from='UTF-8', to='UTF-8')
  category <- e %>% 
    iconv(from='UTF-8', to='UTF-8') %>%
    gsub(pattern='.*"keywords": \\["(.+?)"\\].*', '\\1', x=.)
  clicked <- e %>% html_nodes('.clicked') %>% 
    html_text() %>% 
    iconv(from='UTF-8', to='UTF-8')  
  data.frame(content = content, title = title, dt=dt,category=category, 
             clicked=clicked,stringsAsFactors = FALSE )
}
```

## 測試頁面抓取

```{r, result=FALSE}
getArticle('http://www.appledaily.com.tw/realtimenews/article/life/20160415/839550/')
```

## 抓取清單連結
```{r}
domain = 'http://www.appledaily.com.tw'
getURL <- function(newsurl){
  apple <- read_html(newsurl, encoding="UTF-8")  
  rtddt <- apple %>% html_nodes('.rtddt')  
  url <- rtddt %>% html_nodes('a') %>% html_attr('href')
  url <- gsub(domain, "", url)
  url <- paste0(domain, url) 
  df <- lapply(url, getArticle)
  
  dfall <- do.call("rbind", df)
  dfall
} 	

```

## 測試清單抓取
```{r}
a<- getURL('http://www.appledaily.com.tw/realtimenews/section/new/')

```

## 抓取多頁資料
```{r}
pageurl <- 'http://www.appledaily.com.tw/realtimenews/section/new/'
dfall <- lapply(1:2, 
                function(i){
                  url <- paste0(pageurl, i)
                  df <- getURL(url)
                } 
)
appledaily <- do.call("rbind", dfall)
```

## 讀取網路上的資料檔
```{r}
download.file('https://raw.githubusercontent.com/ywchiu/rtibame/master/appledaily.RData', 'appledaily.RData')
load('appledaily.RData')
```

## 儲存爬取下來的資料檔
```{r}
save(appledaily, file="appledaily.RData")
```

## 可以印出該資料的輪廓
```{r}
class(appledaily)
dim(appledaily)
str(appledaily)

```

## 可以印出該資料的輪廓
```{r}
appledaily[1,"content"]

appledaily[1,"content"] %>% strsplit("googletag") %>% .[[1]] %>% .[1]
```

## 使用strsplit 分割字串
```{r}
a <- 'aaa@bbb@ccc'
strsplit(a,'@')
```


## 使用strsplit 分割字串
```{r}
a <- 'aaa@bbb@ccc'
strsplit(a,'@')
```


## 去除掉所有文章前後空白
```{r}
appledaily[1,"content"] %>% strsplit("googletag") %>% .[[1]] %>% .[1] %>% trimws()

```

## 使用strsplit 與 paste 完成清理函式
```{r}
appledaily[1,"content"] %>% strsplit("googletag") %>% .[[1]] %>% .[1] %>% trimws() %>% strsplit('[ \n\r]+') %>% unlist() %>% paste(collapse=' ')


```

## 修改原本的content 欄位內容
```{r}
contentclean <- function(news){
    news %>% strsplit("googletag") %>% .[[1]] %>% .[1] %>% trimws() %>% strsplit('[ \n\r]+') %>% unlist() %>% paste(collapse=' ')
}
appledaily$content <- sapply(appledaily$content, contentclean)

```
## 抓出點閱數字
```{r}
appledaily[1,"clicked"] %>% 
      gsub('.*\\((\\d+)\\)','\\1', x=.)

```


## 修改點閱數字
```{r}
appledaily$view_cnt <- appledaily$clicked %>% 
     gsub('.*\\((\\d+)\\)','\\1', x=.)

```

## 移除Clicked 欄位
```{r}
appledaily$clicked = NULL
```

## 時間轉換
```{r}
appledaily$dt <- strptime(appledaily$dt, "%Y年%m月%d日%H:%M")
appledaily$dt <- as.POSIXct(appledaily$dt)

```
